# Site settings
title: Guillermo Villanueva 
description: Personal Website
author: Guillermo

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge


permalink: /:title
  
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag

# Navigation menu
links:
  - title: About
    url: /index.html
  - title: Projects
    url: /articles/index.html
  - title: CV
    url: /assets/CV_guillermo_villanueva.pdf

# Social-icons
social:
- {icon: 'github',     link: 'https://www.github.com/guillermovillanuevabenito'}
- {icon: 'linkedin',   link: 'https://www.linkedin.com/in/guillermo-villanueva-130691234/'}
- {icon: 'envelope',   link: 'mailto:guillermovillanuevabenito@gmail.com'}

sharing_button_prompt: 'Feel free to share!'

post_date_prefix: 'Written on'

paginate: 4;
paginate_path: "/articles/index/page:num/"

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
